# Generated by Django 2.2 on 2020-03-16 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IPPool', '0003_auto_20200316_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxyip',
            name='score',
            field=models.IntegerField(default=100, verbose_name='得分'),
        ),
    ]
