# Generated by Django 2.2 on 2020-03-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IPPool', '0004_auto_20200316_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxyip',
            name='protocol',
            field=models.CharField(default='', max_length=10, verbose_name='代理类型'),
        ),
    ]
